# Use an official phpMyAdmin image
FROM phpmyadmin/phpmyadmin:latest

# Optional: Add custom PHP configurations if needed.
# For example, to increase upload limits:
# COPY php.ini /usr/local/etc/php/conf.d/php-custom.ini 